# 2.4G Dongle Receiver
CONFIG_ZMK_2G4_DONGLE=y
CONFIG_ZMK_2G4_AES_KEY="6D6164656279706864656973676EC0DE"

# # USB
CONFIG_ZMK_USB=y
# CONFIG_USB_DEVICE_PID=0xFF10
# CONFIG_USB_DEVICE_PRODUCT="PH-Dongle"

# No BLE on dongle
CONFIG_ZMK_BLE=n

# HID
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
CONFIG_ZMK_HID_INDICATORS=y

# No sleep on dongle (always USB powered)
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=0
