CONFIG_ZMK_STUDIO_LOCKING=n

# 2.4GHz Wireless
CONFIG_SRAM_VECTOR_TABLE=y
CONFIG_ZMK_2G4=y
CONFIG_ZMK_2G4_RF_CHANNEL=76
CONFIG_ZMK_2G4_TX_POWER=8
CONFIG_ZMK_2G4_RETRANSMIT_COUNT=4
CONFIG_ZMK_2G4_RETRANSMIT_DELAY=500
CONFIG_ZMK_2G4_AES_KEY="6D6164656279706864656973676EC0DE"

# Flash writes must bypass BLE ticker timeslot when ESB uses radio
CONFIG_SOC_FLASH_NRF_RADIO_SYNC_NONE=y
