# 2.4GHz Wireless
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
CONFIG_SRAM_VECTOR_TABLE=y
CONFIG_ZMK_2G4=y
CONFIG_ZMK_2G4_RF_CHANNEL=76
CONFIG_ZMK_2G4_TX_POWER=8
CONFIG_ZMK_2G4_RETRANSMIT_COUNT=4
CONFIG_ZMK_2G4_RETRANSMIT_DELAY=500
CONFIG_ZMK_2G4_AES_KEY="f8c813b7336a0adb2a30f89dcb8b7b0e"

# Flash writes must bypass BLE ticker timeslot when ESB uses radio
CONFIG_SOC_FLASH_NRF_RADIO_SYNC_NONE=y