# Uncomment the following lines to enable RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Uncomment the following line to enable OLED Display
# CONFIG_ZMK_DISPLAY=y

# Better wireless performance
CONFIG_BT_CTLR_TX_PWR_PLUS_4=y
CONFIG_HEAP_MEM_POOL_SIZE=16384

# BLE throughput optimization (faster ZMK Studio over BLE)
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_BT_BUF_ACL_TX_SIZE=251
CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_L2CAP_TX_MTU=247

# Enable BLE experimental features
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

# Debounce configuration
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=2
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=6

# Low Power States - Go to sleep after 300 mins (300*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=18000000
CONFIG_ZMK_IDLE_SKIP_ON_USB_POWER=y

CONFIG_ZMK_SLEEP=y

# Soft Off
CONFIG_ZMK_PM_SOFT_OFF=y

# USB Device Configuration
CONFIG_USB_DEVICE_PID=0xF002
CONFIG_USB_DEVICE_PRODUCT="PH60-Multi_V2"
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Mouse Keys
CONFIG_ZMK_POINTING=y

# 2.4GHz Wireless
CONFIG_SRAM_VECTOR_TABLE=y
CONFIG_ZMK_2G4=y
CONFIG_ZMK_2G4_RF_CHANNEL=76
CONFIG_ZMK_2G4_TX_POWER=8
CONFIG_ZMK_2G4_RETRANSMIT_COUNT=4
CONFIG_ZMK_2G4_RETRANSMIT_DELAY=500
CONFIG_ZMK_2G4_AES_KEY="6D6164656279706864656973676EC0DE"

# Flash writes must bypass BLE ticker timeslot when ESB uses radio
CONFIG_SOC_FLASH_NRF_RADIO_SYNC_NONE=y